services:
  - type: web
    name: pantrypal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn PantryPal.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: PantryPal.settings
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: pantrypal-db
          property: connectionString
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: pantrypal-cex0.onrender.com
    staticRoutes:
      - type: static
        name: media
        path: /media/*
        source: media/
databases:
  - name: pantrypal-db
    databaseName: pantrypal
    user: pantrypal_user 