# Generated by Django 5.2.1 on 2025-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_savedrecipe_sharedrecipe_recipevote_recipecomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedrecipe",
            old_name="meal_photo",
            new_name="image",
        ),
        migrations.AddField(
            model_name="savedrecipe",
            name="hash",
            field=models.CharField(default="default_hash", max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="savedrecipe",
            name="ingredients",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="savedrecipe",
            name="instructions",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="savedrecipe",
            name="tags",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
