# Generated by Django 5.2.1 on 2025-06-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0004_rename_meal_photo_savedrecipe_image_savedrecipe_hash_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedrecipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="shared_meals/"),
        ),
    ]
