# Generated by Django 5.2.1 on 2025-06-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_savedrecipe_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedrecipe",
            name="meal_photo",
        ),
    ]
