# Generated by Django 5.2.1 on 2025-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_recipe_alter_savedrecipe_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedrecipe",
            name="hash",
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="hash",
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
