# Generated by Django 5.2.1 on 2025-06-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_generatedrecipe_hash_recipe_hash"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipecomment",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="reciperating",
            old_name="user",
            new_name="rater",
        ),
        migrations.RenameField(
            model_name="sharedrecipe",
            old_name="user",
            new_name="author",
        ),
        migrations.AlterUniqueTogether(
            name="reciperating",
            unique_together={("rater", "recipe")},
        ),
    ]
