# Generated by Django 5.2.1 on 2025-06-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_useractivity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedrecipe",
            name="user_photo",
        ),
    ]
