# Generated by Django 5.2.1 on 2025-06-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_remove_sharedrecipe_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipecomment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="comment_photos/"),
        ),
    ]
