# Generated by Django 5.2.1 on 2025-06-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_recipecomment_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedrecipe",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("generated", "Generated"),
                    ("saved", "Saved Recipe"),
                    ("shared", "Shared Recipe"),
                    ("unshared", "Unshared Recipe"),
                    ("unsaved", "Unsaved Recipe"),
                    ("commented", "Commented"),
                    ("rated", "Rated Recipe"),
                    ("email_changed", "Changed Email"),
                    ("password_changed", "Changed Password"),
                ],
                max_length=32,
            ),
        ),
    ]
