# Generated by Django 5.2.1 on 2025-07-01 11:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0013_alter_generatedrecipe_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="recipes/",
            ),
        ),
    ]
