# Generated by Django 5.2.1 on 2025-07-01 12:27

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0014_alter_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipecomment",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="comment_photos/",
            ),
        ),
    ]
